jdk: oraclejdk8
language: android
android: 
  components: 
    - tools
    - platform-tools
    - build-tools-22.0.1
    - android-22  
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
    - extra-google-google_play_services
cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: 
  - "./gradlew build connectedCheck --stacktrace"